/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */
import { faker } from "@faker-js/faker";
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  GetApiV1IndexCcbotJson200,
  GetApiV1IndexCollinfoJson200Item,
  GetApiV1IndexGraphinfoJson200Item,
} from "./model";

export const getGetApiV1IndexCcbotJsonResponseMock =
  (): GetApiV1IndexCcbotJson200 => ({
    creationTime: "2025-06-23T17:02:06.734458",
    prefixes: [
      { ipv6Prefix: "2600:1f28:365:80b0::/60" },
      { ipv4Prefix: "18.97.9.168/29" },
      { ipv4Prefix: "18.97.14.80/29" },
      { ipv4Prefix: "18.97.14.88/30" },
      { ipv4Prefix: "98.85.178.216/32" },
    ],
  });

export const getGetApiV1IndexByCollResponseMock = (): string | Blob =>
  faker.helpers.arrayElement([
    'com,example)/ 20260206181759 {"url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "951", "offset": "607115282", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505396.36/warc/CC-MAIN-20260206181458-20260206211458-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}\ncom,example)/ 20260206222421 {"url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "953", "offset": "572768496", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505610.3/warc/CC-MAIN-20260206211956-20260207001956-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}',
    '{"urlkey": "com,example)/", "timestamp": "20260206181759", "url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "951", "offset": "607115282", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505396.36/warc/CC-MAIN-20260206181458-20260206211458-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}\n{"urlkey": "com,example)/", "timestamp": "20260206222421", "url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "953", "offset": "572768496", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505610.3/warc/CC-MAIN-20260206211956-20260207001956-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}',
    '<https://www.example.com/>; rel="memento"; datetime="Fri, 06 Feb 2026 18:17:59 GMT",\n<https://www.example.com/>; rel="memento"; datetime="Fri, 06 Feb 2026 22:24:21 GMT"',
    "com,example)/ 20260206181759 https://www.example.com/ text/html text/html 200 JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ 951 607115282 crawl-data/CC-MAIN-2026-08/segments/1770395505396.36/warc/CC-MAIN-20260206181458-20260206211458-00865.warc.gz eng ISO-8859-1\ncom,example)/ 20260206222421 https://www.example.com/ text/html text/html 200 JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ 953 572768496 crawl-data/CC-MAIN-2026-08/segments/1770395505610.3/warc/CC-MAIN-20260206211956-20260207001956-00865.warc.gz eng ISO-8859-1",
  ]);

export const getGetApiV1IndexByCollTimemapJsonByUrlResponseMock = (): string =>
  '{"urlkey": "com,example)/", "timestamp": "20260206181759", "url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "951", "offset": "607115282", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505396.36/warc/CC-MAIN-20260206181458-20260206211458-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}\n{"urlkey": "com,example)/", "timestamp": "20260206222421", "url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "953", "offset": "572768496", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505610.3/warc/CC-MAIN-20260206211956-20260207001956-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}';

export const getGetApiV1IndexByCollTimemapLinkByUrlResponseMock =
  (): ArrayBuffer =>
    new TextEncoder().encode(
      '<https://index.commoncrawl.org/CC-MAIN-2026-08/timemap/link/https://example.com/>; rel="self"; type="application/link-format"; from="Fri, 06 Feb 2026 18:17:59 GMT",\n<https://index.commoncrawl.org/CC-MAIN-2026-08/https://example.com/>; rel="timegate",\n<https://example.com/>; rel="original",\n<https://index.commoncrawl.org/CC-MAIN-2026-08/20260206181759/https://www.example.com/>; rel="memento"; datetime="Fri, 06 Feb 2026 18:17:59 GMT",\n<https://index.commoncrawl.org/CC-MAIN-2026-08/20260206222421/https://www.example.com/>; rel="memento"; datetime="Fri, 06 Feb 2026 22:24:21 GMT"',
    ).buffer;

export const getGetApiV1IndexByCollTimemapCdxjByUrlResponseMock = (): string =>
  'com,example)/ 20260206181759 {"url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "951", "offset": "607115282", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505396.36/warc/CC-MAIN-20260206181458-20260206211458-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}\ncom,example)/ 20260206222421 {"url": "https://www.example.com/", "mime": "text/html", "mime-detected": "text/html", "status": "200", "digest": "JUWMXAQNHPTRTHYQWT3EJILYCL7YC3PQ", "length": "953", "offset": "572768496", "filename": "crawl-data/CC-MAIN-2026-08/segments/1770395505610.3/warc/CC-MAIN-20260206211956-20260207001956-00865.warc.gz", "languages": "eng", "encoding": "ISO-8859-1"}';

export const getGetApiV1IndexByCollByTimestampByUrlResponseMock = ():
  | string
  | ArrayBuffer =>
  faker.helpers.arrayElement([
    '<!doctype html><html lang="en"><head>\n<!-- WB Insert -->\n<script>\nwbinfo = {};\nwbinfo.top_url = "https://index.commoncrawl.org/CC-MAIN-2026-08/20260206181759/https://www.example.com/";\nwbinfo.url = "https://www.example.com/";\nwbinfo.timestamp = "20260206181759";\n</script>\n</head><body></body></html>',
    "\\u0089PNG\\r\\n\\u001a\\n\\u0000\\u0000\\u0000\\rIHDR...",
  ]);

export const getGetApiV1IndexByCollByUrlResponseMock = ():
  | string
  | ArrayBuffer =>
  faker.helpers.arrayElement([
    '<!doctype html><html lang="en"><head>\n<!-- WB Insert -->\n<script>\nwbinfo = {};\nwbinfo.top_url = "https://index.commoncrawl.org/CC-MAIN-2026-08/20260206181759/https://www.example.com/";\nwbinfo.url = "https://www.example.com/";\nwbinfo.timestamp = "20260206181759";\n</script>\n</head><body></body></html>',
    "\\u0089PNG\\r\\n\\u001a\\n\\u0000\\u0000\\u0000\\rIHDR...",
  ]);

export const getGetApiV1IndexCollinfoJsonResponseMock =
  (): GetApiV1IndexCollinfoJson200Item[] => [
    {
      id: "CC-MAIN-2026-08",
      name: "February 2026 Index",
      timegate: "https://index.commoncrawl.org/CC-MAIN-2026-08/",
      "cdx-api": "https://index.commoncrawl.org/CC-MAIN-2026-08-index",
      from: "2026-02-06T18:14:58",
      to: "2026-02-19T11:27:33",
    },
    {
      id: "CC-MAIN-2026-04",
      name: "January 2026 Index",
      timegate: "https://index.commoncrawl.org/CC-MAIN-2026-04/",
      "cdx-api": "https://index.commoncrawl.org/CC-MAIN-2026-04-index",
      from: "2026-01-12T16:12:39",
      to: "2026-01-25T14:05:40",
    },
    {
      id: "CC-MAIN-2025-51",
      name: "December 2025 Index",
      timegate: "https://index.commoncrawl.org/CC-MAIN-2025-51/",
      "cdx-api": "https://index.commoncrawl.org/CC-MAIN-2025-51-index",
      from: "2025-12-04T19:18:28",
      to: "2025-12-17T14:22:46",
    },
  ];

export const getGetApiV1IndexGraphinfoJsonResponseMock =
  (): GetApiV1IndexGraphinfoJson200Item[] => [
    {
      id: "cc-main-2025-26-dec-jan-feb",
      crawls: ["CC-MAIN-2025-51", "CC-MAIN-2026-04", "CC-MAIN-2026-08"],
      index:
        "https://data.commoncrawl.org/projects/hyperlinkgraph/cc-main-2025-26-dec-jan-feb/index.html",
      location:
        "s3://commoncrawl/projects/hyperlinkgraph/cc-main-2025-26-dec-jan-feb/",
      stats: {
        host: { nodes: 288604261, arcs: 12365071120 },
        domain: { nodes: 134222466, arcs: 5380423856 },
      },
    },
    {
      id: "cc-main-2025-26-nov-dec-jan",
      crawls: ["CC-MAIN-2025-47", "CC-MAIN-2025-51", "CC-MAIN-2026-04"],
      index:
        "https://data.commoncrawl.org/projects/hyperlinkgraph/cc-main-2025-26-nov-dec-jan/index.html",
      location:
        "s3://commoncrawl/projects/hyperlinkgraph/cc-main-2025-26-nov-dec-jan/",
      stats: {
        host: { nodes: 279356058, arcs: 13431887360 },
        domain: { nodes: 122294847, arcs: 6112336768 },
      },
    },
    {
      id: "cc-main-2025-oct-nov-dec",
      crawls: ["CC-MAIN-2025-43", "CC-MAIN-2025-47", "CC-MAIN-2025-51"],
      index:
        "https://data.commoncrawl.org/projects/hyperlinkgraph/cc-main-2025-oct-nov-dec/index.html",
      location:
        "s3://commoncrawl/projects/hyperlinkgraph/cc-main-2025-oct-nov-dec/",
      stats: {
        host: { nodes: 250753325, arcs: 10858559096 },
        domain: { nodes: 121304598, arcs: 6220780848 },
      },
    },
  ];

export const getGetApiV1IndexCcbotJsonMockHandler = (
  overrideResponse?:
    | GetApiV1IndexCcbotJson200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetApiV1IndexCcbotJson200> | GetApiV1IndexCcbotJson200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/ccbot.json",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexCcbotJsonResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetApiV1IndexByCollMockHandler = (
  overrideResponse?:
    | string
    | Blob
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string | Blob> | string | Blob),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollResponseMock();
      return typeof resolvedBody === "string"
        ? HttpResponse.text(resolvedBody, { status: 200 })
        : HttpResponse.json(resolvedBody, { status: 200 });
    },
    options,
  );
};

export const getGetApiV1IndexByCollTimemapJsonByUrlMockHandler = (
  overrideResponse?:
    | string
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll/timemap/json/:url",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollTimemapJsonByUrlResponseMock();
      const textBody =
        typeof resolvedBody === "string"
          ? resolvedBody
          : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.text(textBody, { status: 200 });
    },
    options,
  );
};

export const getGetApiV1IndexByCollTimemapLinkByUrlMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll/timemap/link/:url",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollTimemapLinkByUrlResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        {
          status: 200,
          headers: { "Content-Type": "application/octet-stream" },
        },
      );
    },
    options,
  );
};

export const getGetApiV1IndexByCollTimemapCdxjByUrlMockHandler = (
  overrideResponse?:
    | string
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll/timemap/cdxj/:url",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollTimemapCdxjByUrlResponseMock();
      const textBody =
        typeof resolvedBody === "string"
          ? resolvedBody
          : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.text(textBody, { status: 200 });
    },
    options,
  );
};

export const getGetApiV1IndexByCollByTimestampByUrlMockHandler = (
  overrideResponse?:
    | string
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string | ArrayBuffer> | string | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll/:timestamp/:url",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollByTimestampByUrlResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        {
          status: 200,
          headers: { "Content-Type": "application/octet-stream" },
        },
      );
    },
    options,
  );
};

export const getGetApiV1IndexByCollByUrlMockHandler = (
  overrideResponse?:
    | string
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string | ArrayBuffer> | string | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/:coll/:url",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexByCollByUrlResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        {
          status: 200,
          headers: { "Content-Type": "application/octet-stream" },
        },
      );
    },
    options,
  );
};

export const getGetApiV1IndexCollinfoJsonMockHandler = (
  overrideResponse?:
    | GetApiV1IndexCollinfoJson200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetApiV1IndexCollinfoJson200Item[]>
        | GetApiV1IndexCollinfoJson200Item[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/collinfo.json",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexCollinfoJsonResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetApiV1IndexGraphinfoJsonMockHandler = (
  overrideResponse?:
    | GetApiV1IndexGraphinfoJson200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetApiV1IndexGraphinfoJson200Item[]>
        | GetApiV1IndexGraphinfoJson200Item[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/index/graphinfo.json",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiV1IndexGraphinfoJsonResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getCommonCrawlIndexServerAPIProxyMock = () => [
  getGetApiV1IndexCcbotJsonMockHandler(),
  getGetApiV1IndexByCollMockHandler(),
  getGetApiV1IndexByCollTimemapJsonByUrlMockHandler(),
  getGetApiV1IndexByCollTimemapLinkByUrlMockHandler(),
  getGetApiV1IndexByCollTimemapCdxjByUrlMockHandler(),
  getGetApiV1IndexByCollByTimestampByUrlMockHandler(),
  getGetApiV1IndexByCollByUrlMockHandler(),
  getGetApiV1IndexCollinfoJsonMockHandler(),
  getGetApiV1IndexGraphinfoJsonMockHandler(),
];
