/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */
import { orvalFetch } from "@/api/fetcher";
export type GetApiV1IndexCcbotJson200PrefixesItem =
  | {
      ipv4Prefix: string;
    }
  | {
      ipv6Prefix: string;
    };

export type GetApiV1IndexCcbotJson200 = {
  creationTime: string;
  prefixes: GetApiV1IndexCcbotJson200PrefixesItem[];
};

export type GetApiV1IndexByColl400 = {
  message: string;
};

export type GetApiV1IndexCollinfoJson200Item = {
  id: string;
  name: string;
  timegate: string;
  "cdx-api": string;
  from: string;
  to: string;
};

export type GetApiV1IndexGraphinfoJson200ItemStatsHost = {
  nodes: number;
  arcs: number;
};

export type GetApiV1IndexGraphinfoJson200ItemStatsDomain = {
  nodes: number;
  arcs: number;
};

export type GetApiV1IndexGraphinfoJson200ItemStats = {
  host: GetApiV1IndexGraphinfoJson200ItemStatsHost;
  domain: GetApiV1IndexGraphinfoJson200ItemStatsDomain;
};

export type GetApiV1IndexGraphinfoJson200Item = {
  id: string;
  crawls: string[];
  index: string;
  location: string;
  stats: GetApiV1IndexGraphinfoJson200ItemStats;
};

export type getApiV1IndexCcbotJsonResponse200 = {
  data: GetApiV1IndexCcbotJson200;
  status: 200;
};

export type getApiV1IndexCcbotJsonResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexCcbotJsonResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexCcbotJsonResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexCcbotJsonResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexCcbotJsonResponseSuccess =
  getApiV1IndexCcbotJsonResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexCcbotJsonResponseError = (
  | getApiV1IndexCcbotJsonResponse429TextPlain
  | getApiV1IndexCcbotJsonResponse429TextHtml
  | getApiV1IndexCcbotJsonResponse503TextPlain
  | getApiV1IndexCcbotJsonResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexCcbotJsonResponse =
  | getApiV1IndexCcbotJsonResponseSuccess
  | getApiV1IndexCcbotJsonResponseError;

export const getGetApiV1IndexCcbotJsonUrl = () => {
  return `/api/v1/index/ccbot.json`;
};

export const getApiV1IndexCcbotJson = async (
  options?: RequestInit,
): Promise<getApiV1IndexCcbotJsonResponse> => {
  return orvalFetch<getApiV1IndexCcbotJsonResponse>(
    getGetApiV1IndexCcbotJsonUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * The following is a reference of the api for querying and filtering archived resources.

The api can be used to get information about a range of archive captures/mementos, including filtering, sorting, and pagination for bulk query.

The actual archive files (WARC/ARC) files are not loaded during this query, only the generated CDXJ index.
 * @summary CDXJ Server API
 */
export type getApiV1IndexByCollResponse200TextXCdxj = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollResponse200TextXNdjson = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollResponse200ApplicationLinkFormat = {
  data: Blob;
  status: 200;
};

export type getApiV1IndexByCollResponse200TextPlain = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollResponse400 = {
  data: GetApiV1IndexByColl400;
  status: 400;
};

export type getApiV1IndexByCollResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollResponseSuccess = (
  | getApiV1IndexByCollResponse200TextXCdxj
  | getApiV1IndexByCollResponse200TextXNdjson
  | getApiV1IndexByCollResponse200ApplicationLinkFormat
  | getApiV1IndexByCollResponse200TextPlain
) & {
  headers: Headers;
};
export type getApiV1IndexByCollResponseError = (
  | getApiV1IndexByCollResponse400
  | getApiV1IndexByCollResponse404
  | getApiV1IndexByCollResponse429TextPlain
  | getApiV1IndexByCollResponse429TextHtml
  | getApiV1IndexByCollResponse503TextPlain
  | getApiV1IndexByCollResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollResponse =
  | getApiV1IndexByCollResponseSuccess
  | getApiV1IndexByCollResponseError;

export const getGetApiV1IndexByCollUrl = (coll: string) => {
  return `/api/v1/index/${coll}`;
};

export const getApiV1IndexByColl = async (
  coll: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollResponse> => {
  return orvalFetch<getApiV1IndexByCollResponse>(
    getGetApiV1IndexByCollUrl(coll),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * The timemap API is available at ``/<coll>/timemap/<type>/<url>`` for any pywb collection ``<coll>`` and ``<url>`` in the collection.
 * @summary TimeMap API
 */
export type getApiV1IndexByCollTimemapJsonByUrlResponse200 = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponseSuccess =
  getApiV1IndexByCollTimemapJsonByUrlResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexByCollTimemapJsonByUrlResponseError = (
  | getApiV1IndexByCollTimemapJsonByUrlResponse404
  | getApiV1IndexByCollTimemapJsonByUrlResponse429TextPlain
  | getApiV1IndexByCollTimemapJsonByUrlResponse429TextHtml
  | getApiV1IndexByCollTimemapJsonByUrlResponse503TextPlain
  | getApiV1IndexByCollTimemapJsonByUrlResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollTimemapJsonByUrlResponse =
  | getApiV1IndexByCollTimemapJsonByUrlResponseSuccess
  | getApiV1IndexByCollTimemapJsonByUrlResponseError;

export const getGetApiV1IndexByCollTimemapJsonByUrlUrl = (
  coll: string,
  url: string,
) => {
  return `/api/v1/index/${coll}/timemap/json/${url}`;
};

export const getApiV1IndexByCollTimemapJsonByUrl = async (
  coll: string,
  url: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollTimemapJsonByUrlResponse> => {
  return orvalFetch<getApiV1IndexByCollTimemapJsonByUrlResponse>(
    getGetApiV1IndexByCollTimemapJsonByUrlUrl(coll, url),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * The timemap API is available at ``/<coll>/timemap/<type>/<url>`` for any pywb collection ``<coll>`` and ``<url>`` in the collection.
 * @summary TimeMap API
 */
export type getApiV1IndexByCollTimemapLinkByUrlResponse200 = {
  data: Blob;
  status: 200;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponseSuccess =
  getApiV1IndexByCollTimemapLinkByUrlResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexByCollTimemapLinkByUrlResponseError = (
  | getApiV1IndexByCollTimemapLinkByUrlResponse404
  | getApiV1IndexByCollTimemapLinkByUrlResponse429TextPlain
  | getApiV1IndexByCollTimemapLinkByUrlResponse429TextHtml
  | getApiV1IndexByCollTimemapLinkByUrlResponse503TextPlain
  | getApiV1IndexByCollTimemapLinkByUrlResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollTimemapLinkByUrlResponse =
  | getApiV1IndexByCollTimemapLinkByUrlResponseSuccess
  | getApiV1IndexByCollTimemapLinkByUrlResponseError;

export const getGetApiV1IndexByCollTimemapLinkByUrlUrl = (
  coll: string,
  url: string,
) => {
  return `/api/v1/index/${coll}/timemap/link/${url}`;
};

export const getApiV1IndexByCollTimemapLinkByUrl = async (
  coll: string,
  url: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollTimemapLinkByUrlResponse> => {
  return orvalFetch<getApiV1IndexByCollTimemapLinkByUrlResponse>(
    getGetApiV1IndexByCollTimemapLinkByUrlUrl(coll, url),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * The timemap API is available at ``/<coll>/timemap/<type>/<url>`` for any pywb collection ``<coll>`` and ``<url>`` in the collection.
 * @summary TimeMap API
 */
export type getApiV1IndexByCollTimemapCdxjByUrlResponse200 = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponseSuccess =
  getApiV1IndexByCollTimemapCdxjByUrlResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexByCollTimemapCdxjByUrlResponseError = (
  | getApiV1IndexByCollTimemapCdxjByUrlResponse404
  | getApiV1IndexByCollTimemapCdxjByUrlResponse429TextPlain
  | getApiV1IndexByCollTimemapCdxjByUrlResponse429TextHtml
  | getApiV1IndexByCollTimemapCdxjByUrlResponse503TextPlain
  | getApiV1IndexByCollTimemapCdxjByUrlResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollTimemapCdxjByUrlResponse =
  | getApiV1IndexByCollTimemapCdxjByUrlResponseSuccess
  | getApiV1IndexByCollTimemapCdxjByUrlResponseError;

export const getGetApiV1IndexByCollTimemapCdxjByUrlUrl = (
  coll: string,
  url: string,
) => {
  return `/api/v1/index/${coll}/timemap/cdxj/${url}`;
};

export const getApiV1IndexByCollTimemapCdxjByUrl = async (
  coll: string,
  url: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollTimemapCdxjByUrlResponse> => {
  return orvalFetch<getApiV1IndexByCollTimemapCdxjByUrlResponse>(
    getGetApiV1IndexByCollTimemapCdxjByUrlUrl(coll, url),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * pywb supports the Memento Protocol as specified in RFC 7089 and provides API endpoints for Memento TimeMaps and TimeGates per collection.
 * @summary Memento API
 */
export type getApiV1IndexByCollByTimestampByUrlResponse200TextHtml = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollByTimestampByUrlResponse200ApplicationOctetStream =
  {
    data: Blob;
    status: 200;
  };

export type getApiV1IndexByCollByTimestampByUrlResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollByTimestampByUrlResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollByTimestampByUrlResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollByTimestampByUrlResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollByTimestampByUrlResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollByTimestampByUrlResponseSuccess = (
  | getApiV1IndexByCollByTimestampByUrlResponse200TextHtml
  | getApiV1IndexByCollByTimestampByUrlResponse200ApplicationOctetStream
) & {
  headers: Headers;
};
export type getApiV1IndexByCollByTimestampByUrlResponseError = (
  | getApiV1IndexByCollByTimestampByUrlResponse404
  | getApiV1IndexByCollByTimestampByUrlResponse429TextPlain
  | getApiV1IndexByCollByTimestampByUrlResponse429TextHtml
  | getApiV1IndexByCollByTimestampByUrlResponse503TextPlain
  | getApiV1IndexByCollByTimestampByUrlResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollByTimestampByUrlResponse =
  | getApiV1IndexByCollByTimestampByUrlResponseSuccess
  | getApiV1IndexByCollByTimestampByUrlResponseError;

export const getGetApiV1IndexByCollByTimestampByUrlUrl = (
  coll: string,
  timestamp: string,
  url: string,
) => {
  return `/api/v1/index/${coll}/${timestamp}/${url}`;
};

export const getApiV1IndexByCollByTimestampByUrl = async (
  coll: string,
  timestamp: string,
  url: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollByTimestampByUrlResponse> => {
  return orvalFetch<getApiV1IndexByCollByTimestampByUrlResponse>(
    getGetApiV1IndexByCollByTimestampByUrlUrl(coll, timestamp, url),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * The TimeGate API for any pywb collection is ``/<coll>/<url>``, eg. ``/my-coll/http://example.com/``.
 * @summary TimeGate API
 */
export type getApiV1IndexByCollByUrlResponse200TextHtml = {
  data: string;
  status: 200;
};

export type getApiV1IndexByCollByUrlResponse200ApplicationOctetStream = {
  data: Blob;
  status: 200;
};

export type getApiV1IndexByCollByUrlResponse404 = {
  data: string;
  status: 404;
};

export type getApiV1IndexByCollByUrlResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollByUrlResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexByCollByUrlResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollByUrlResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexByCollByUrlResponseSuccess = (
  | getApiV1IndexByCollByUrlResponse200TextHtml
  | getApiV1IndexByCollByUrlResponse200ApplicationOctetStream
) & {
  headers: Headers;
};
export type getApiV1IndexByCollByUrlResponseError = (
  | getApiV1IndexByCollByUrlResponse404
  | getApiV1IndexByCollByUrlResponse429TextPlain
  | getApiV1IndexByCollByUrlResponse429TextHtml
  | getApiV1IndexByCollByUrlResponse503TextPlain
  | getApiV1IndexByCollByUrlResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexByCollByUrlResponse =
  | getApiV1IndexByCollByUrlResponseSuccess
  | getApiV1IndexByCollByUrlResponseError;

export const getGetApiV1IndexByCollByUrlUrl = (coll: string, url: string) => {
  return `/api/v1/index/${coll}/${url}`;
};

export const getApiV1IndexByCollByUrl = async (
  coll: string,
  url: string,
  options?: RequestInit,
): Promise<getApiV1IndexByCollByUrlResponse> => {
  return orvalFetch<getApiV1IndexByCollByUrlResponse>(
    getGetApiV1IndexByCollByUrlUrl(coll, url),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiV1IndexCollinfoJsonResponse200 = {
  data: GetApiV1IndexCollinfoJson200Item[];
  status: 200;
};

export type getApiV1IndexCollinfoJsonResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexCollinfoJsonResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexCollinfoJsonResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexCollinfoJsonResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexCollinfoJsonResponseSuccess =
  getApiV1IndexCollinfoJsonResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexCollinfoJsonResponseError = (
  | getApiV1IndexCollinfoJsonResponse429TextPlain
  | getApiV1IndexCollinfoJsonResponse429TextHtml
  | getApiV1IndexCollinfoJsonResponse503TextPlain
  | getApiV1IndexCollinfoJsonResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexCollinfoJsonResponse =
  | getApiV1IndexCollinfoJsonResponseSuccess
  | getApiV1IndexCollinfoJsonResponseError;

export const getGetApiV1IndexCollinfoJsonUrl = () => {
  return `/api/v1/index/collinfo.json`;
};

export const getApiV1IndexCollinfoJson = async (
  options?: RequestInit,
): Promise<getApiV1IndexCollinfoJsonResponse> => {
  return orvalFetch<getApiV1IndexCollinfoJsonResponse>(
    getGetApiV1IndexCollinfoJsonUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiV1IndexGraphinfoJsonResponse200 = {
  data: GetApiV1IndexGraphinfoJson200Item[];
  status: 200;
};

export type getApiV1IndexGraphinfoJsonResponse429TextPlain = {
  data: string;
  status: 429;
};

export type getApiV1IndexGraphinfoJsonResponse429TextHtml = {
  data: string;
  status: 429;
};

export type getApiV1IndexGraphinfoJsonResponse503TextPlain = {
  data: string;
  status: 503;
};

export type getApiV1IndexGraphinfoJsonResponse503TextHtml = {
  data: string;
  status: 503;
};

export type getApiV1IndexGraphinfoJsonResponseSuccess =
  getApiV1IndexGraphinfoJsonResponse200 & {
    headers: Headers;
  };
export type getApiV1IndexGraphinfoJsonResponseError = (
  | getApiV1IndexGraphinfoJsonResponse429TextPlain
  | getApiV1IndexGraphinfoJsonResponse429TextHtml
  | getApiV1IndexGraphinfoJsonResponse503TextPlain
  | getApiV1IndexGraphinfoJsonResponse503TextHtml
) & {
  headers: Headers;
};

export type getApiV1IndexGraphinfoJsonResponse =
  | getApiV1IndexGraphinfoJsonResponseSuccess
  | getApiV1IndexGraphinfoJsonResponseError;

export const getGetApiV1IndexGraphinfoJsonUrl = () => {
  return `/api/v1/index/graphinfo.json`;
};

export const getApiV1IndexGraphinfoJson = async (
  options?: RequestInit,
): Promise<getApiV1IndexGraphinfoJsonResponse> => {
  return orvalFetch<getApiV1IndexGraphinfoJsonResponse>(
    getGetApiV1IndexGraphinfoJsonUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};
