/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */

export type GetApiV1IndexGraphinfoJson200ItemStatsDomain = {
  nodes: number;
  arcs: number;
};
