/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiV1IndexGraphinfoJson200ItemStats } from "./getApiV1IndexGraphinfoJson200ItemStats";

export type GetApiV1IndexGraphinfoJson200Item = {
  id: string;
  crawls: string[];
  index: string;
  location: string;
  stats: GetApiV1IndexGraphinfoJson200ItemStats;
};
