/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiV1IndexGraphinfoJson200ItemStatsDomain } from "./getApiV1IndexGraphinfoJson200ItemStatsDomain";
import type { GetApiV1IndexGraphinfoJson200ItemStatsHost } from "./getApiV1IndexGraphinfoJson200ItemStatsHost";

export type GetApiV1IndexGraphinfoJson200ItemStats = {
  host: GetApiV1IndexGraphinfoJson200ItemStatsHost;
  domain: GetApiV1IndexGraphinfoJson200ItemStatsDomain;
};
