/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Common Crawl Index Server API Proxy
 * Development documentation
 * OpenAPI spec version: 0.0.1
 */
import type { GetApiV1IndexCcbotJson200PrefixesItem } from "./getApiV1IndexCcbotJson200PrefixesItem";

export type GetApiV1IndexCcbotJson200 = {
  creationTime: string;
  prefixes: GetApiV1IndexCcbotJson200PrefixesItem[];
};
